use_frameworks!

platform :ios, '10.0'

target 'StyleUI_Example' do
  pod 'StyleUI', :path => '../'

  target 'StyleUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
